global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: email-me

receivers:
- name: email-me
  email_configs:
  - send_resolved: true
    to: <email-address> # multiple email addresses seperated by comma
    from: <email-address>
    smarthost: smtp.gmail.com:587
    auth_username: "<email-address>"
    auth_identity: "<email-address>"
    auth_password: "<app-password>"

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
