services:
  blackbox_exporter:
    image: quay.io/prometheus/blackbox-exporter:latest
    container_name: blackbox_exporter
    networks:
      - monitoring
    volumes:
      - ./blackbox_exporter:/config
    command: "--config.file=/config/blackbox.yml"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - monitoring
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    depends_on:
      - blackbox_exporter
      - alertmanager
    command: "--config.file=/etc/prometheus/prometheus.yml"
    restart: unless-stopped

  alertmanager:
    image: quay.io/prometheus/alertmanager
    container_name: alertmanager
    networks:
      - monitoring
    volumes:
      - ./alertmanager:/etc/alertmanager
    command: "--config.file=/etc/alertmanager/alertmanager.yml"
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      - monitoring
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: unless-stopped

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

  smart_ocr:
    image: mightysanjay/smart-ocr:v1
    container_name: smart_ocr
    networks:
      - monitoring
    ports:
      - "5001:5000"
    restart: unless-stopped

networks:
  monitoring:
    driver: bridge
